# Generated by Django 5.0.2 on 2024-10-10 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='fullname'),
            preserve_default=False,
        ),
    ]
